[package]
name = "pxxl-tls"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
pxxl-common = { path = "../common" }
async-trait = { workspace = true }
rcgen = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
