[workspace]
members = ["edge", "edge/crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0"
arc-swap = "1.7"
argon2 = "0.5"
async-trait = "0.1"
base64 = "0.22"
bytes = "1.7"
chrono = { version = "0.4", features = ["serde"] }
dashmap = "6.1"
flate2 = "1.0"
futures-util = "0.3"
http = "1.1"
http-body-util = "0.1"
hyper = { version = "1.5", features = ["client", "http1", "http2", "server"] }
hyper-rustls = { version = "0.27", features = ["http1", "http2", "native-tokio"] }
hyper-util = { version = "0.1", features = ["client", "client-legacy", "http1", "http2", "server", "server-auto", "tokio"] }
ipnet = { version = "2.10", features = ["serde"] }
jsonwebtoken = "9.3"
maxminddb = "0.27"
parking_lot = "0.12"
prometheus = "0.13"
rcgen = "0.12"
redis = { version = "0.27", features = ["tokio-comp"] }
rustls = "0.23"
rustls-pemfile = "2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
tempfile = "3.12"
thiserror = "2.0"
tokio = { version = "1.41", features = ["full"] }
tokio-rustls = "0.26"
toml = "0.8"
tower-service = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
url = "2.5"
uuid = { version = "1.10", features = ["v4", "serde"] }
x509-parser = "0.16"
