services:
  edge:
    group_add:
      - "0"
    environment:
      PXXL_DOCKER_ENABLED: ${PXXL_DOCKER_ENABLED:-false}
      PXXL_DOCKER_SOCKET_PATH: /var/run/docker.sock
      PXXL_PODMAN_ENABLED: ${PXXL_PODMAN_ENABLED:-true}
      PXXL_PODMAN_SOCKET_PATH: /var/run/podman/podman.sock
      PXXL_PODMAN_PUBLISHED_HOST: ${PXXL_PODMAN_PUBLISHED_HOST:-host.docker.internal}
    volumes:
      - ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - ${PODMAN_SOCKET_PATH:-/run/user/1002/podman/podman.sock}:/var/run/podman/podman.sock:ro
